const fs = require("fs");
const Anthropic = require("@anthropic-ai/sdk");
const OP_CableSpecDocument = require("../operations/OP_CableSpecDocument");

const client = new Anthropic();

// ─── Section field lists ──────────────────────────────────────────────────
// Each leaf field is generated as { value, confidence, reason } so the
// review UI can show every AI-suggested value alongside its confidence and
// justification, per the design brief. Every value stays fully editable
// downstream - this only shapes what the model returns.

const CONDUCTOR_FIELDS = [
  "material", "class", "noOfStrands", "strandDiameter", "overallDiameter",
  "maxResistance", "weight", "area", "fillFactor",
];

const INSULATION_FIELDS = [
  "material", "nominalThickness", "minimumThickness", "maximumThickness",
  "overallDiameter", "colour", "tensileBeforeAgeing", "tensileAfterAgeing",
  "elongationBeforeAgeing", "elongationAfterAgeing", "sparkTestVoltage",
  "density", "volumeResistivity", "temperatureRating",
];

const CORE_IDENTIFICATION_FIELDS = [
  "colour", "numberPrinting", "numberingType", "stripe", "inkPrinting",
];

const LAYING_UP_FIELDS = [
  "layDirection", "layLength", "binderTape", "binderThickness",
  "separator", "fillers", "percentageFill",
];

const INNER_SHEATH_FIELDS = [
  "material", "thickness", "diameter", "colour", "weight", "tolerance",
];

const ARMOURING_FIELDS = [
  "armourType", "steelWire", "steelStrip", "aluminiumWire", "wireDiameter",
  "numberOfWires", "coverage", "weight",
];

const OUTER_SHEATH_FIELDS = [
  "material", "thickness", "overallDiameter", "colour", "printing",
  "embossing", "sparkTest", "weight",
];

const ELECTRICAL_PROPERTIES_FIELDS = [
  "maxConductorResistance", "insulationResistance", "capacitance",
  "inductance", "reactance", "currentCarryingCapacity",
  "shortCircuitRating", "voltageDrop", "powerLoss",
];

const MECHANICAL_PROPERTIES_FIELDS = [
  "minimumBendingRadius", "cableWeight", "maximumPullingForce",
  "crushingLoad", "impactTest", "flameTest", "smokeDensity",
  "oilResistance", "uvResistance",
];

const MANUFACTURING_PROCESS_FIELDS = [
  "wireDrawing", "annealing", "stranding", "insulationExtrusion", "cooling",
  "sparkTest", "coreLaying", "binding", "innerSheath", "armouring",
  "outerSheath", "printing", "testing", "packing",
];

const SECTIONS = {
  conductor: CONDUCTOR_FIELDS,
  insulation: INSULATION_FIELDS,
  coreIdentification: CORE_IDENTIFICATION_FIELDS,
  layingUp: LAYING_UP_FIELDS,
  innerSheath: INNER_SHEATH_FIELDS,
  armouring: ARMOURING_FIELDS,
  outerSheath: OUTER_SHEATH_FIELDS,
  electricalProperties: ELECTRICAL_PROPERTIES_FIELDS,
  mechanicalProperties: MECHANICAL_PROPERTIES_FIELDS,
  manufacturingProcess: MANUFACTURING_PROCESS_FIELDS,
};

// The full schema (10 sections x ~9 fields x {value, confidence, reason}) is too large
// for Anthropic's structured-output (output_config.format) grammar compiler - it 400s
// with "compiled grammar is too large" well before the field count gets here. So instead
// of a strict json_schema, the required shape is described in the prompt and the
// response is parsed as plain JSON (see parseJsonResponse below).
function describeOutputStructure() {
  return Object.entries(SECTIONS)
    .map(([section, fields]) => `- "${section}": { ${fields.join(", ")} }`)
    .join("\n");
}

const OUTPUT_FORMAT_INSTRUCTIONS = `Respond with ONLY a single JSON object - no markdown code fences, no commentary before or after it.
The object must have exactly these top-level keys, each an object with exactly the listed fields (no extra or missing fields):
${describeOutputStructure()}

Every field's value must be an object of this exact shape:
{ "value": "<string, the generated value - numbers are still strings, e.g. \\"2.5\\">", "confidence": <number 0-100>, "reason": "<string, standard/spec/practice this is based on>" }`;

function parseJsonResponse(text) {
  const fenced = text.match(/```(?:json)?\s*([\s\S]*?)\s*```/);
  const jsonText = fenced ? fenced[1] : text;
  return JSON.parse(jsonText);
}

const SYSTEM_PROMPT = `You are an expert Cable Design Engineer with more than 30 years of experience in LV, MV, HV, Instrumentation, Control, Solar, Automotive, Flexible, and Building cables.

Your responsibility is to generate an accurate cable design based on user inputs and international standards (IS, IEC, BS, ASTM, UL, VDE, customer specifications).

Rules:
- Generate the design using IEC/IS/ASTM/BS standards, common company design practice, and the customer specification if provided.
- If multiple values are possible, choose the most commonly used industrial value.
- Never leave any field blank - always provide your best engineering estimate.
- Material prices are NEVER generated by you. Do not include any pricing/cost figures anywhere in the output - costing is calculated separately by the ERP from its Material Master.
- For every field you generate, also return a confidence percentage (0-100) and a short reason (e.g. "Based on IEC 60228", "Based on IS 694", "Based on customer specification", "Based on industry practice").
- Every value you return is a starting recommendation only - the engineer reviewing it can edit, delete, or override any field, so prefer a sensible concrete value over hedging.

${OUTPUT_FORMAT_INSTRUCTIONS}`;

function buildRetrievalQuery(rfq) {
  return [
    rfq.cable_type, rfq.cable_standard, rfq.conductor_material,
    rfq.insulation_material, rfq.voltage_grade, rfq.customer_specification,
    rfq.special_requirement,
  ].filter(Boolean).join(" ");
}

function buildUserPrompt(rfq, referenceChunks) {
  const lines = [
    `Cable Type: ${rfq.cable_type}`,
    `Cable Standard: ${rfq.cable_standard}`,
    `Conductor Size: ${rfq.conductor_size} sq.mm`,
    `Number of Core: ${rfq.no_of_core}`,
    `Conductor Material: ${rfq.conductor_material}`,
    `Insulation Material: ${rfq.insulation_material}`,
    `Voltage Grade: ${rfq.voltage_grade}`,
    `Operating Temperature: ${rfq.operating_temperature}`,
  ];
  if (rfq.customer_specification) {
    lines.push(`Customer Specification: ${rfq.customer_specification}`);
  }
  if (rfq.special_requirement) {
    lines.push(`Special Requirement: ${rfq.special_requirement}`);
  }

  if (referenceChunks.length) {
    lines.push(
      "",
      "Reference material from uploaded cable specification/standard documents (use where relevant, prefer these over general knowledge when they conflict):",
    );
    referenceChunks.forEach((chunk, i) => {
      const source = chunk.cable_standard ? `${chunk.file_name} (${chunk.cable_standard})` : chunk.file_name;
      lines.push(`--- Excerpt ${i + 1} from ${source} ---`, chunk.chunk_text);
    });
  }

  lines.push("", "Generate the complete cable design per the JSON structure described in your instructions.");
  return lines.join("\n");
}

const EXTRACTION_SYSTEM_PROMPT = `You are an expert Cable Design Engineer with more than 30 years of experience in LV, MV, HV, Instrumentation, Control, Solar, Automotive, Flexible, and Building cables.

You will be given a cable specification/standard document (e.g. IEC, IS, BS, ASTM). Extract the cable design parameters defined in the output schema based on what this document actually specifies.

Rules:
- Prefer values explicitly stated in the document. When the document gives a range or a table of options, choose the most commonly used/representative value and say so in the reason.
- If the document does not explicitly cover a field, provide your best engineering estimate based on the document's overall standard and general industry practice, and give it a lower confidence score reflecting that it's inferred rather than stated.
- Never leave any field blank - always provide a concrete value.
- Material prices are NEVER generated by you. Do not include any pricing/cost figures anywhere in the output.
- For every field, return a confidence percentage (0-100) and a short reason referencing the specific clause/table/section of the document when possible (e.g. "Table 4, IS 5831"), or "Inferred - not explicitly specified in this document" when not.

${OUTPUT_FORMAT_INSTRUCTIONS}`;

exports.extractDesignFromPdf = async function (absolutePdfPath) {
  const pdfBase64 = fs.readFileSync(absolutePdfPath).toString("base64");

  const stream = client.messages.stream({
    model: "claude-opus-5",
    max_tokens: 32000,
    thinking: { type: "adaptive" },
    system: EXTRACTION_SYSTEM_PROMPT,
    messages: [
      {
        role: "user",
        content: [
          { type: "document", source: { type: "base64", media_type: "application/pdf", data: pdfBase64 } },
          { type: "text", text: "Extract the cable design parameters from the attached specification document, per the JSON structure described in your instructions." },
        ],
      },
    ],
  });

  const message = await stream.finalMessage();

  if (message.stop_reason === "refusal") {
    throw new Error("The AI declined to extract data from this document.");
  }

  const textBlock = message.content.find((block) => block.type === "text");
  if (!textBlock) {
    throw new Error("AI response did not contain extracted data.");
  }

  return parseJsonResponse(textBlock.text);
};

exports.generateDesign = async function (rfq) {
  const referenceChunks = await OP_CableSpecDocument.retrieveRelevantChunks(buildRetrievalQuery(rfq));

  const stream = client.messages.stream({
    model: "claude-opus-5",
    max_tokens: 32000,
    thinking: { type: "adaptive" },
    system: SYSTEM_PROMPT,
    messages: [
      { role: "user", content: buildUserPrompt(rfq, referenceChunks) },
    ],
  });

  const message = await stream.finalMessage();

  if (message.stop_reason === "refusal") {
    throw new Error("The AI declined to generate this design. Please review the RFQ inputs and try again.");
  }

  const textBlock = message.content.find((block) => block.type === "text");
  if (!textBlock) {
    throw new Error("AI response did not contain a design.");
  }

  return parseJsonResponse(textBlock.text);
};

// ─── Quick Conductor & Insulation design ───────────────────────────────────
// A small, focused tool distinct from the full generateDesign() flow above:
// 4 basic inputs in, a flat set of conductor+insulation construction values
// out (no confidence/reason wrapper - these are meant to populate editable
// input boxes directly). Schema is small enough to use strict structured
// output (unlike the ~89-field full design schema, which hits Anthropic's
// grammar-size limit - see OUTPUT_FORMAT_INSTRUCTIONS above).
const CONDUCTOR_TYPE_OPTIONS = ["Aluminium", "Bare Copper", "Tinned Copper"];
const CONDUCTOR_CLASS_OPTIONS = ["Class 1 (Solid)", "Class 2 (Semi Flex)", "Class 5 (Flexible)", "Class 6 (Super Flex)"];

// Business rule: Aluminium conductors are always Class 2 (Semi Flex); Bare/Tinned Copper
// are always Class 5 (Flexible). Enforced by narrowing the schema's enum to that single
// value (a hard guarantee, not just a prompt instruction) so the model can't pick another.
const FORCED_CONDUCTOR_CLASS_BY_MATERIAL = {
  "Aluminium": "Class 2 (Semi Flex)",
  "Bare Copper": "Class 5 (Flexible)",
  "Tinned Copper": "Class 5 (Flexible)",
};

function quickDesignOutputSchema(includeOuterSheath, forcedClass) {
  const numericField = (description) => ({ type: "string", description: `${description} Numeric value only, no units (e.g. "7.41" not "7.41 ohm/km").` });
  const properties = {
    conductorType: { type: "string", enum: CONDUCTOR_TYPE_OPTIONS, description: "Conductor material type." },
    class: {
      type: "string",
      enum: forcedClass ? [forcedClass] : CONDUCTOR_CLASS_OPTIONS,
      description: "Conductor construction class.",
    },
    noOfStrands: numericField("Number of strands in the conductor."),
    diaOfStrands: numericField("Diameter of each strand, in mm."),
    maxConductorResistance: numericField("Maximum DC resistance of the conductor at 20°C, in ohm/km."),
    insulationMaterial: { type: "string", description: "Insulation compound grade, e.g. 'PVC Type A' or 'XLPE'." },
    thickness: numericField("Nominal insulation thickness, in mm."),
    diaOfInsulation: numericField("Overall diameter over insulation, in mm."),
    colour: { type: "string", description: "Insulation colour." },
    tensileBeforeAgeing: numericField("Tensile strength before ageing, in N/mm2."),
    tensileAfterAgeing: numericField("Tensile strength after ageing, in N/mm2."),
    elongationBeforeAgeing: numericField("Elongation at break before ageing, in %."),
    elongationAfterAgeing: numericField("Elongation at break after ageing, in %."),
    sparkTest: numericField("Spark test voltage, in kV."),
  };
  if (includeOuterSheath) {
    // outerSheathMaterial is a user-provided input for multi-core cables (like conductor/
    // insulation material), not generated here - only its resulting construction values are.
    properties.outerSheathThickness = numericField("Nominal outer sheath thickness, in mm, for the given outer sheath material.");
    properties.outerSheathColour = { type: "string", description: "Outer sheath colour." };
    properties.outerSheathOverallDiameter = numericField("Overall diameter of the finished multi-core cable over the outer sheath, in mm.");
  }
  return {
    type: "object",
    properties,
    required: Object.keys(properties),
    additionalProperties: false,
  };
}

const QUICK_DESIGN_SYSTEM_PROMPT = `You are an expert Cable Design Engineer with more than 30 years of experience in LV, MV, HV, Instrumentation, Control, Solar, Automotive, Flexible, and Building cables.

Given a basic cable specification, generate the conductor and insulation construction parameters defined in the output schema.

Rules:
- Use IEC/IS/ASTM/BS standards and common industrial practice appropriate to the given conductor size, core count, and materials.
- If multiple values are possible, choose the most commonly used industrial value for that conductor size.
- Never leave any field blank - always provide a concrete value.
- Numeric fields must be plain numbers with no units in the string (e.g. "7.41", not "7.41 ohm/km" or "~7.4").
- Material prices are NEVER generated by you.`;

function buildQuickDesignUserPrompt(input, includeOuterSheath, forcedClass) {
  const lines = [
    `Conductor Size: ${input.conductorSize} sq.mm`,
    `Number of Cores: ${input.noOfCores}`,
    `Conductor Material: ${input.conductorMaterial}`,
    `Insulation Material: ${input.insulationMaterial}`,
  ];
  if (includeOuterSheath) {
    lines.push(`Outer Sheath Material: ${input.outerSheathMaterial}`);
  }
  if (forcedClass) {
    lines.push(`Conductor Class: Must be exactly "${forcedClass}" for ${input.conductorMaterial} conductor material - generate the strand count and strand diameter consistent with this class.`);
  }
  lines.push("", "Generate the conductor and insulation construction parameters defined in the output schema.");
  if (includeOuterSheath) {
    lines.push("This is a multi-core cable - also generate the outer sheath (laid up over all cores) thickness, colour, and overall diameter for the given outer sheath material.");
  }
  return lines.join("\n");
}

exports.generateConductorInsulationDesign = async function (input) {
  const includeOuterSheath = Number(input.noOfCores) > 1;
  const forcedClass = FORCED_CONDUCTOR_CLASS_BY_MATERIAL[input.conductorMaterial];

  const stream = client.messages.stream({
    model: "claude-opus-5",
    max_tokens: 8000,
    thinking: { type: "adaptive" },
    system: QUICK_DESIGN_SYSTEM_PROMPT,
    output_config: {
      format: {
        type: "json_schema",
        schema: quickDesignOutputSchema(includeOuterSheath, forcedClass),
      },
    },
    messages: [
      { role: "user", content: buildQuickDesignUserPrompt(input, includeOuterSheath, forcedClass) },
    ],
  });

  const message = await stream.finalMessage();

  if (message.stop_reason === "refusal") {
    throw new Error("The AI declined to generate this design. Please review the inputs and try again.");
  }

  const textBlock = message.content.find((block) => block.type === "text");
  if (!textBlock) {
    throw new Error("AI response did not contain a design.");
  }

  return JSON.parse(textBlock.text);
};
