const Anthropic = require("@anthropic-ai/sdk");

const client = new Anthropic();

// ─── Section field lists ──────────────────────────────────────────────────
// Each leaf field is generated as { value, confidence, reason } so the
// review UI can show every AI-suggested value alongside its confidence and
// justification, per the design brief. Every value stays fully editable
// downstream - this only shapes what the model returns.

const CONDUCTOR_FIELDS = [
  "material", "class", "noOfStrands", "strandDiameter", "overallDiameter",
  "maxResistance", "weight", "area", "fillFactor",
];

const INSULATION_FIELDS = [
  "material", "nominalThickness", "minimumThickness", "maximumThickness",
  "overallDiameter", "colour", "tensileBeforeAgeing", "tensileAfterAgeing",
  "elongationBeforeAgeing", "elongationAfterAgeing", "sparkTestVoltage",
  "density", "volumeResistivity", "temperatureRating",
];

const CORE_IDENTIFICATION_FIELDS = [
  "colour", "numberPrinting", "numberingType", "stripe", "inkPrinting",
];

const LAYING_UP_FIELDS = [
  "layDirection", "layLength", "binderTape", "binderThickness",
  "separator", "fillers", "percentageFill",
];

const INNER_SHEATH_FIELDS = [
  "material", "thickness", "diameter", "colour", "weight", "tolerance",
];

const ARMOURING_FIELDS = [
  "armourType", "steelWire", "steelStrip", "aluminiumWire", "wireDiameter",
  "numberOfWires", "coverage", "weight",
];

const OUTER_SHEATH_FIELDS = [
  "material", "thickness", "overallDiameter", "colour", "printing",
  "embossing", "sparkTest", "weight",
];

const ELECTRICAL_PROPERTIES_FIELDS = [
  "maxConductorResistance", "insulationResistance", "capacitance",
  "inductance", "reactance", "currentCarryingCapacity",
  "shortCircuitRating", "voltageDrop", "powerLoss",
];

const MECHANICAL_PROPERTIES_FIELDS = [
  "minimumBendingRadius", "cableWeight", "maximumPullingForce",
  "crushingLoad", "impactTest", "flameTest", "smokeDensity",
  "oilResistance", "uvResistance",
];

const MANUFACTURING_PROCESS_FIELDS = [
  "wireDrawing", "annealing", "stranding", "insulationExtrusion", "cooling",
  "sparkTest", "coreLaying", "binding", "innerSheath", "armouring",
  "outerSheath", "printing", "testing", "packing",
];

const SECTIONS = {
  conductor: CONDUCTOR_FIELDS,
  insulation: INSULATION_FIELDS,
  coreIdentification: CORE_IDENTIFICATION_FIELDS,
  layingUp: LAYING_UP_FIELDS,
  innerSheath: INNER_SHEATH_FIELDS,
  armouring: ARMOURING_FIELDS,
  outerSheath: OUTER_SHEATH_FIELDS,
  electricalProperties: ELECTRICAL_PROPERTIES_FIELDS,
  mechanicalProperties: MECHANICAL_PROPERTIES_FIELDS,
  manufacturingProcess: MANUFACTURING_PROCESS_FIELDS,
};

function fieldSchema() {
  return {
    type: "object",
    properties: {
      value: { type: ["string", "number"], description: "The generated value for this field." },
      confidence: { type: "number", description: "Confidence percentage from 0 to 100." },
      reason: { type: "string", description: "Standard/spec/practice this value is based on, e.g. 'Based on IEC 60228'." },
    },
    required: ["value", "confidence", "reason"],
    additionalProperties: false,
  };
}

function sectionSchema(fields) {
  const properties = {};
  for (const field of fields) {
    properties[field] = fieldSchema();
  }
  return {
    type: "object",
    properties,
    required: fields,
    additionalProperties: false,
  };
}

function buildOutputSchema() {
  const properties = {};
  for (const [section, fields] of Object.entries(SECTIONS)) {
    properties[section] = sectionSchema(fields);
  }
  return {
    type: "object",
    properties,
    required: Object.keys(SECTIONS),
    additionalProperties: false,
  };
}

const SYSTEM_PROMPT = `You are an expert Cable Design Engineer with more than 30 years of experience in LV, MV, HV, Instrumentation, Control, Solar, Automotive, Flexible, and Building cables.

Your responsibility is to generate an accurate cable design based on user inputs and international standards (IS, IEC, BS, ASTM, UL, VDE, customer specifications).

Rules:
- Generate the design using IEC/IS/ASTM/BS standards, common company design practice, and the customer specification if provided.
- If multiple values are possible, choose the most commonly used industrial value.
- Never leave any field blank - always provide your best engineering estimate.
- Material prices are NEVER generated by you. Do not include any pricing/cost figures anywhere in the output - costing is calculated separately by the ERP from its Material Master.
- For every field you generate, also return a confidence percentage (0-100) and a short reason (e.g. "Based on IEC 60228", "Based on IS 694", "Based on customer specification", "Based on industry practice").
- Every value you return is a starting recommendation only - the engineer reviewing it can edit, delete, or override any field, so prefer a sensible concrete value over hedging.`;

function buildUserPrompt(rfq) {
  const lines = [
    `Cable Type: ${rfq.cable_type}`,
    `Cable Standard: ${rfq.cable_standard}`,
    `Conductor Size: ${rfq.conductor_size} sq.mm`,
    `Number of Core: ${rfq.no_of_core}`,
    `Conductor Material: ${rfq.conductor_material}`,
    `Insulation Material: ${rfq.insulation_material}`,
    `Voltage Grade: ${rfq.voltage_grade}`,
    `Operating Temperature: ${rfq.operating_temperature}`,
  ];
  if (rfq.customer_specification) {
    lines.push(`Customer Specification: ${rfq.customer_specification}`);
  }
  if (rfq.special_requirement) {
    lines.push(`Special Requirement: ${rfq.special_requirement}`);
  }
  lines.push("", "Generate the complete cable design for the sections defined in the output schema.");
  return lines.join("\n");
}

exports.generateDesign = async function (rfq) {
  const stream = client.messages.stream({
    model: "claude-opus-5",
    max_tokens: 32000,
    thinking: { type: "adaptive" },
    system: SYSTEM_PROMPT,
    output_config: {
      format: {
        type: "json_schema",
        schema: buildOutputSchema(),
      },
    },
    messages: [
      { role: "user", content: buildUserPrompt(rfq) },
    ],
  });

  const message = await stream.finalMessage();

  if (message.stop_reason === "refusal") {
    throw new Error("The AI declined to generate this design. Please review the RFQ inputs and try again.");
  }

  const textBlock = message.content.find((block) => block.type === "text");
  if (!textBlock) {
    throw new Error("AI response did not contain a design.");
  }

  return JSON.parse(textBlock.text);
};
