const ROOT_BASE_URL_MASTERS = '/api/masters';

const apiActivityLogger = require("../../services/apiActivityLogger");

module.exports = async (app, jwt) => {
	app.use(ROOT_BASE_URL_MASTERS + '/usersMaster', jwt, apiActivityLogger, require('../masters/usersMasterAPI'));
	app.use(ROOT_BASE_URL_MASTERS + '/designationMaster', jwt, apiActivityLogger, require('../masters/designationMasterAPI'));
    app.use(ROOT_BASE_URL_MASTERS + '/countryMaster', jwt,apiActivityLogger, require('../masters/countryMasterAPI'));
	app.use(ROOT_BASE_URL_MASTERS + '/stateMaster', jwt, apiActivityLogger, require('../masters/stateMasterAPI'));
	app.use(ROOT_BASE_URL_MASTERS + '/cityMaster', jwt, apiActivityLogger, require('../masters/cityMasterAPI'));
	app.use(ROOT_BASE_URL_MASTERS + '/departmentMaster', jwt, apiActivityLogger, require('../masters/departmentMasterAPI'));
	app.use(ROOT_BASE_URL_MASTERS + '/wireCableTypeMaster', jwt, apiActivityLogger, require('../masters/wireCableTypesMasterAPI'));
	app.use(ROOT_BASE_URL_MASTERS + '/cableCategoryMaster', jwt, apiActivityLogger, require('../masters/cableCategoryMasterAPI'));
	app.use(ROOT_BASE_URL_MASTERS + '/cableStageMaster', jwt, apiActivityLogger, require('../masters/cableStageMasterAPI'));
	app.use(ROOT_BASE_URL_MASTERS + '/stageMaster', jwt, apiActivityLogger, require('../masters/stageMasterAPI'));
	app.use(ROOT_BASE_URL_MASTERS + '/unitTypeMaster', jwt, apiActivityLogger, require('../masters/unitTypeMasterAPI'));
	app.use(ROOT_BASE_URL_MASTERS + '/materialMaster', jwt, apiActivityLogger, require('../masters/materialMasterAPI'));
	app.use(ROOT_BASE_URL_MASTERS + '/paymentTermMaster', jwt, apiActivityLogger, require('../masters/paymentTermMasterAPI'));
	app.use(ROOT_BASE_URL_MASTERS + '/itemMaster', jwt, apiActivityLogger, require('../masters/itemMasterAPI'));
	app.use(ROOT_BASE_URL_MASTERS + '/relationMaster', jwt, apiActivityLogger, require('../masters/relationMasterAPI'));
	app.use(ROOT_BASE_URL_MASTERS + '/bankMaster', jwt, apiActivityLogger, require('../masters/bankMasterAPI'));
	app.use(ROOT_BASE_URL_MASTERS + '/leaveTypeMaster', jwt, apiActivityLogger, require('../masters/leaveTypeMasterAPI'));
	app.use(ROOT_BASE_URL_MASTERS + '/expenseTypeMaster', jwt, apiActivityLogger, require('../masters/expenseTypeMasterAPI'));
	app.use(ROOT_BASE_URL_MASTERS + '/classMaster', jwt, apiActivityLogger, require('../masters/classMasterAPI'));
	app.use(ROOT_BASE_URL_MASTERS + '/sectionMaster', jwt, apiActivityLogger, require('../masters/sectionMasterAPI'));
	app.use(ROOT_BASE_URL_MASTERS + '/studentMaster', jwt, apiActivityLogger, require('../masters/studentMasterAPI'));
	app.use(ROOT_BASE_URL_MASTERS + '/studentParentsMaster', jwt, apiActivityLogger, require('../masters/studentParentsMasterAPI'));
	app.use(ROOT_BASE_URL_MASTERS + '/studentDocument', jwt, apiActivityLogger, require('../masters/studentDocumentAPI'));
	app.use(ROOT_BASE_URL_MASTERS + '/emailMaster', jwt, apiActivityLogger, require('../masters/emailMasterAPI'));
	app.use(ROOT_BASE_URL_MASTERS + '/mobileMaster', jwt, apiActivityLogger, require('../masters/mobileMasterAPI'));
	app.use(ROOT_BASE_URL_MASTERS + '/addressMaster', jwt, apiActivityLogger, require('../masters/addressMasterAPI'));
	app.use(ROOT_BASE_URL_MASTERS + '/academicMaster', jwt, apiActivityLogger, require('../masters/academicMasterAPI'));
	app.use(ROOT_BASE_URL_MASTERS + '/subjectMaster', jwt, apiActivityLogger, require('../masters/subjectMasterAPI'));
	app.use(ROOT_BASE_URL_MASTERS + '/feeTypeMaster', jwt, apiActivityLogger, require('../masters/feeTypeMasterAPI'));
	app.use(ROOT_BASE_URL_MASTERS + '/newsTypeMaster', jwt, apiActivityLogger, require('../masters/newsTypeMasterAPI'));
	app.use(ROOT_BASE_URL_MASTERS + '/priorityMaster', jwt, apiActivityLogger, require('../masters/priorityMasterAPI'));
	app.use(ROOT_BASE_URL_MASTERS + '/emailTemplateMaster', jwt, apiActivityLogger, require('../masters/emailTemplateMasterAPI'));
	app.use(ROOT_BASE_URL_MASTERS + '/documentTypeMaster', jwt, apiActivityLogger, require('../masters/documentTypeMasterAPI'));
	app.use(ROOT_BASE_URL_MASTERS + '/dropdownMaster', jwt, apiActivityLogger, require('../masters/dropdownMasterAPI'));
	app.use(ROOT_BASE_URL_MASTERS + '/dropdownValueMaster', jwt, apiActivityLogger, require('../masters/dropdownValueMasterAPI'));
	app.use(ROOT_BASE_URL_MASTERS + '/assetMaster', jwt, apiActivityLogger, require('../masters/assetMasterAPI'));
};
