INSERT INTO public.dropdown_value_master
(field_id, field_value, status, is_deleted, created_by, created_date)
VALUES
(17, 'Performance Incentive', 1, 0, 1, NOW()),
(17, 'Attendance Incentive', 1, 0, 1, NOW()),
(17, 'Production Incentive', 1, 0, 1, NOW()),
(17, 'Sales Incentive', 1, 0, 1, NOW()),
(17, 'Target Achievement Incentive', 1, 0, 1, NOW()),
(17, 'Quality Incentive', 1, 0, 1, NOW()),
(17, 'Safety Incentive', 1, 0, 1, NOW()),
(17, 'Team Performance Incentive', 1, 0, 1, NOW()),
(17, 'Project Completion Incentive', 1, 0, 1, NOW()),
(17, 'Referral Incentive', 1, 0, 1, NOW()),
(17, 'Retention Incentive', 1, 0, 1, NOW()),
(17, 'Shift Incentive', 1, 0, 1, NOW()),
(17, 'Overtime Incentive', 1, 0, 1, NOW()),
(17, 'Productivity Incentive', 1, 0, 1, NOW()),
(17, 'Customer Satisfaction Incentive', 1, 0, 1, NOW()),
(17, 'Innovation Incentive', 1, 0, 1, NOW()),
(17, 'Suggestion Incentive', 1, 0, 1, NOW()),
(17, 'Profit Sharing Incentive', 1, 0, 1, NOW()),
(17, 'Commission', 1, 0, 1, NOW()),
(17, 'Skill-Based Incentive', 1, 0, 1, NOW()),
(17, 'Training Completion Incentive', 1, 0, 1, NOW()),
(17, 'Leadership Incentive', 1, 0, 1, NOW()),
(17, 'Special Achievement Incentive', 1, 0, 1, NOW()),
(17, 'Cost Saving Incentive', 1, 0, 1, NOW()),
(17, 'Inventory Accuracy Incentive', 1, 0, 1, NOW()),
(17, 'On-Time Delivery Incentive', 1, 0, 1, NOW()),
(17, 'Machine Efficiency Incentive', 1, 0, 1, NOW()),
(17, 'Scrap Reduction Incentive', 1, 0, 1, NOW()),
(17, 'Annual Performance Incentive', 1, 0, 1, NOW()),
(17, 'Festival Incentive', 1, 0, 1, NOW()),
(17, 'Loyalty Incentive', 1, 0, 1, NOW()),
(17, 'Joining Incentive', 1, 0, 1, NOW()),
(17, 'Spot Award Incentive', 1, 0, 1, NOW()),
(17, 'Digital Adoption Incentive', 1, 0, 1, NOW()),
(17, 'Compliance Incentive', 1, 0, 1, NOW());