-- Per-employee, per-period incentive accrual ledger. incentive_master defines the scheme
-- (name, type, value, frequency, scope); this table is the actual accrued installment for
-- one employee in one period, generated by the accrueEmployeeIncentiveDetails cron job.
-- Mirrors the users_salary_details -> salary_payments pattern (scheme/master vs ledger).
CREATE TABLE IF NOT EXISTS employee_incentive_details (
  id BIGSERIAL PRIMARY KEY,
  incentive_id INTEGER NOT NULL REFERENCES incentive_master(id),
  employee_id INTEGER NOT NULL REFERENCES users_master(id),
  year INTEGER NOT NULL,
  period_month INTEGER NOT NULL CHECK (period_month BETWEEN 1 AND 12),
  value_type VARCHAR(20) NOT NULL,
  amount NUMERIC(12, 2) NOT NULL,
  basic_da NUMERIC(12, 2),
  status INTEGER NOT NULL DEFAULT 1,
  created_by INTEGER NOT NULL REFERENCES users_master(id),
  created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  modified_by INTEGER REFERENCES users_master(id),
  modified_date TIMESTAMP,
  deleted_by INTEGER REFERENCES users_master(id),
  deleted_date TIMESTAMP,
  UNIQUE (incentive_id, employee_id, year, period_month)
);
COMMENT ON TABLE employee_incentive_details IS 'Per-employee accrued incentive installments, generated by the monthly accrual cron from incentive_master schemes.';
COMMENT ON COLUMN employee_incentive_details.incentive_id IS 'Scheme this installment was accrued from, references incentive_master.';
COMMENT ON COLUMN employee_incentive_details.employee_id IS 'Employee this installment belongs to, references users_master.';
COMMENT ON COLUMN employee_incentive_details.year IS 'Calendar year the installment was accrued for.';
COMMENT ON COLUMN employee_incentive_details.period_month IS 'Calendar month (1-12) the installment was accrued for.';
COMMENT ON COLUMN employee_incentive_details.value_type IS 'Snapshot of incentive_master.value_type (flat/percentage) at accrual time.';
COMMENT ON COLUMN employee_incentive_details.amount IS 'Computed installment amount credited for this period.';
COMMENT ON COLUMN employee_incentive_details.basic_da IS 'Snapshot of employee basic+DA used for percentage-type calculation; NULL for flat.';
COMMENT ON COLUMN employee_incentive_details.status IS '1 = Active, 0 = soft-deleted.';
CREATE INDEX IF NOT EXISTS idx_eid_employee_id ON employee_incentive_details(employee_id);
CREATE INDEX IF NOT EXISTS idx_eid_incentive_id ON employee_incentive_details(incentive_id);
CREATE INDEX IF NOT EXISTS idx_eid_status ON employee_incentive_details(status);
